POST http://localhost:8080/products
Content-Type: "application/json"

{
    "name":"Fone Apple 230TWS",
    "price":100.20
}

###

GET http://localhost:8080/products/ecd4fb8b-a7a8-4e33-8099-0d868ceb57e1
Content-Type: "application/json"

###

PUT http://localhost:8080/products/ecd4fb8b-a7a8-4e33-8099-0d868ceb57e1

{
    "name":"Caneca Linux",
    "price":300.20
}


###

DELETE  http://localhost:8080/products/dc56b970-355d-4535-a9b3-7ce550ac9b61


###

GET http://localhost:8080/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTY3ODgxMDUsInN1YiI6IjU2OTM1MjY2LWU0YTMtNGIxNS1iNGRmLThkM2U3MGExZDIwOSJ9.4-F9Ky8Mx4BPdbT6KolB3-l-ZvUWzZ9vQfDGzUo9foA
Content-Type: "application/json"