POST http://localhost:8080/user
Content-Type: "application/json"

{
    "name":"Julio Sandroni",
    "email":"jo@ig.com",
    "password":"1234"
}

###

POST http://localhost:8080/user/login
Content-Type: "application/json"

{
    "email":"jo@ig.com",
    "password":"1234"
}