basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is exercise swagger go api with Authentication
  title: Stadard GO API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
